# Generated by Django 5.2.17 on 2026-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('lemma', models.TextField()),
                ('sentence', models.TextField()),
                ('sentence_svg_html', models.TextField()),
                ('prev_sentence', models.TextField()),
                ('prev_sentence_svg_html', models.TextField()),
                ('follow_sentence', models.TextField()),
                ('follow_sentence_svg_html', models.TextField()),
                ('treesentences', models.TextField()),
                ('treesentences_svg_html', models.TextField()),
            ],
            options={
                'ordering': ['findingID'],
            },
        ),
    ]
