# Generated by Django 5.2.17 on 2026-10-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('lemma', models.TextField()),
                ('sentence', models.TextField()),
                ('sentence_svg_html', models.TextField()),
                ('prev_sentence', models.TextField()),
                ('prev_sentence_svg_html', models.TextField()),
                ('follow_sentence', models.TextField()),
                ('follow_sentence_svg_html', models.TextField()),
                ('treesentences', models.TextField()),
                ('treesentences_svg_html', models.TextField()),
            ],
            options={
                'ordering': ['findingID'],
            },
        ),
        migrations.CreateModel(
            name='SentenceInAnalyticalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('contains_lemma', models.CharField(choices=[('True', 'Contains Lemma'), ('False', 'Does Not Contain Lemma'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('sentence_type', models.CharField(choices=[('previous_sentence', 'Previous'), ('lemma_sentence', 'Lemma Sentence'), ('following_sentence', 'Following Sentence'), ('other', 'Other')], default='other', max_length=20)),
                ('sentence', models.TextField()),
                ('words_in_sentence', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['findingID'],
            },
        ),
        migrations.CreateModel(
            name='LemmaObjectForAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=250)),
                ('lemma_position', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemmas', to='Lingvistik_app.sentenceinanalyticalcontext')),
            ],
        ),
        migrations.CreateModel(
            name='WordObjectForAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('position', models.IntegerField()),
                ('wordclass', models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('DET', 'Determiner'), ('ADP', 'Adposition'), ('CONJ', 'Conjunction'), ('NUM', 'Numeral'), ('PART', 'Particle'), ('INTJ', 'Interjection'), ('obj', 'Object'), ('X', 'Other')], max_length=50)),
                ('graphic_X_position', models.IntegerField(verbose_name=models.IntegerField())),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='Lingvistik_app.sentenceinanalyticalcontext')),
            ],
        ),
    ]
