# Generated by Django 5.2.17 on 2026-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('treesentences', models.TextField()),
                ('svg_html', models.TextField()),
            ],
        ),
    ]
