# Generated by Django 5.2.17 on 2026-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedsentence',
            old_name='svg_html',
            new_name='sentence',
        ),
        migrations.AddField(
            model_name='parsedsentence',
            name='sentences_svg_html',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsedsentence',
            name='treesentences_svg_html',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
