# Generated by Django 5.2.17 on 2026-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordobjectforanalysis',
            name='graphic_Y_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordobjectforanalysis',
            name='graphic_X_position',
            field=models.IntegerField(default=0),
        ),
    ]
