# Generated by Django 5.2.17 on 2026-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceInAnalyticalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('sentence', models.TextField()),
            ],
            options={
                'ordering': ['findingID'],
            },
        ),
    ]
