# Generated by Django 5.2.17 on 2026-10-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0002_sentenceinanalyticalcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenceinanalyticalcontext',
            name='contains_lemma',
            field=models.CharField(choices=[('True', 'Contains Lemma'), ('False', 'Does Not Contain Lemma'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='sentenceinanalyticalcontext',
            name='sentence_type',
            field=models.CharField(choices=[('previous_sentence', 'Previous'), ('lemma_sentence', 'Lemma Sentence'), ('following_sentence', 'Following Sentence'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='sentenceinanalyticalcontext',
            name='words_in_sentence',
            field=models.IntegerField(null=True),
        ),
    ]
