# Generated by Django 5.2.17 on 2026-10-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0002_wordobjectforanalysis_graphic_y_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualisationOfSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_svg', models.TextField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuel_words', to='Lingvistik_app.sentenceinanalyticalcontext')),
            ],
        ),
    ]
