# Generated by Django 5.2.17 on 2026-09-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0002_rename_svg_html_parsedsentence_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedsentence',
            name='follow_sentences_svg_html',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsedsentence',
            name='prev_sentences_svg_html',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
