# Generated by Django 5.2.17 on 2026-10-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0003_sentenceinanalyticalcontext_contains_lemma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordObjectForAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('position', models.IntegerField()),
                ('wordclass', models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('DET', 'Determiner'), ('ADP', 'Adposition'), ('CONJ', 'Conjunction'), ('NUM', 'Numeral'), ('PART', 'Particle'), ('INTJ', 'Interjection'), ('obj', 'Object'), ('X', 'Other')], max_length=50)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='Lingvistik_app.sentenceinanalyticalcontext')),
            ],
        ),
    ]
