# Generated by Django 5.2.17 on 2026-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0003_parsedsentence_follow_sentences_svg_html_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedsentence',
            old_name='follow_sentences_svg_html',
            new_name='follow_sentence',
        ),
        migrations.RenameField(
            model_name='parsedsentence',
            old_name='prev_sentences_svg_html',
            new_name='follow_sentence_svg_html',
        ),
        migrations.RenameField(
            model_name='parsedsentence',
            old_name='sentences_svg_html',
            new_name='prev_sentence',
        ),
        migrations.AddField(
            model_name='parsedsentence',
            name='prev_sentence_svg_html',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsedsentence',
            name='sentence_svg_html',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
