# Generated by Django 5.2.17 on 2026-10-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0004_wordobjectforanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LemmaObjectForAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=250)),
                ('lemma_position', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemmas', to='Lingvistik_app.sentenceinanalyticalcontext')),
            ],
        ),
    ]
