# Generated by Django 5.2.17 on 2026-09-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0004_rename_follow_sentences_svg_html_parsedsentence_follow_sentence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsedsentence',
            options={'ordering': ['findingID']},
        ),
    ]
