# Generated by Django 5.2.17 on 2026-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0005_alter_parsedsentence_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('sentence_position', models.TextField()),
                ('contains_lemma', models.BooleanField()),
            ],
            options={
                'ordering': ['findingID'],
            },
        ),
        migrations.AddField(
            model_name='parsedsentence',
            name='lemma',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
