# Generated by Django 5.2.17 on 2026-09-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0006_sentencemodifier_parsedsentence_lemma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='SentenceGramma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
            ],
            options={
                'ordering': ['findingID'],
            },
        ),
        migrations.CreateModel(
            name='WordClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Word classes',
            },
        ),
        migrations.CreateModel(
            name='IdentifiedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('positioner', models.ManyToManyField(related_name='identified_words', to='Lingvistik_app.position')),
                ('wordclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='Lingvistik_app.wordclass')),
            ],
            options={
                'verbose_name_plural': 'Identified words',
            },
        ),
    ]
