# Generated by Django 5.2.17 on 2026-09-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0007_position_sentencegramma_wordclass_identifiedwords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentenceGramma',
        ),
    ]
