# Generated by Django 5.2.17 on 2026-10-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lingvistik_app', '0008_delete_sentencegramma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_type', models.CharField(choices=[('previous', 'Previous'), ('lemmasentence', 'Lemma Sentence'), ('followingsentence', 'Following Sentence')], default='lemmasentence', max_length=20)),
                ('sentence', models.TextField()),
                ('wordsinsentence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordsInSentenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('word', models.TextField()),
                ('wordclass', models.TextField()),
                ('wordposition', models.IntegerField()),
            ],
            options={
                'ordering': ['findingID'],
            },
        ),
        migrations.RemoveField(
            model_name='identifiedwords',
            name='positioner',
        ),
        migrations.RemoveField(
            model_name='identifiedwords',
            name='wordclass',
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findingID', models.TextField()),
                ('lemma_position', models.IntegerField()),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemmas', to='Lingvistik_app.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('position', models.IntegerField()),
                ('wordclass', models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('DET', 'Determiner'), ('ADP', 'Adposition'), ('CONJ', 'Conjunction'), ('NUM', 'Numeral'), ('PART', 'Particle'), ('INTJ', 'Interjection'), ('obj', 'Object'), ('X', 'Other')], max_length=50)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='Lingvistik_app.sentence')),
            ],
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='IdentifiedWords',
        ),
        migrations.DeleteModel(
            name='WordClass',
        ),
    ]
